import {
  colorDataVizDangerFill,
  colorDataVizDangerHover,
  colorDataVizDangerLine,
  colorDataVizNeutralFill,
  colorDataVizNeutralHover,
  colorDataVizPrimaryFill,
  colorDataVizPrimaryFillAlt,
  colorDataVizPrimaryHover,
  colorDataVizPrimaryLine,
  colorDataVizSecondaryFill,
  colorDataVizSecondaryFillAlt,
  colorDataVizSecondaryHover,
  colorDataVizSecondaryLine,
  colorDataVizTertiaryFill,
  colorDataVizTertiaryFillAlt,
  colorDataVizTertiaryHover,
  colorDataVizTertiaryLine,
  colorDataVizWarningFill,
  colorDataVizWarningHover,
  colorDataVizWarningLine,
} from '../../constants';

export const dataViz = {
  dangerFill: colorDataVizDangerFill,
  dangerHover: colorDataVizDangerHover,
  dangerLine: colorDataVizDangerLine,
  neutralFill: colorDataVizNeutralFill,
  neutralHover: colorDataVizNeutralHover,
  primaryFill: colorDataVizPrimaryFill,
  primaryFillAlt: colorDataVizPrimaryFillAlt,
  primaryHover: colorDataVizPrimaryHover,
  primaryLine: colorDataVizPrimaryLine,
  secondaryFill: colorDataVizSecondaryFill,
  secondaryFillAlt: colorDataVizSecondaryFillAlt,
  secondaryHover: colorDataVizSecondaryHover,
  secondaryLine: colorDataVizSecondaryLine,
  tertiaryFill: colorDataVizTertiaryFill,
  tertiaryFillAlt: colorDataVizTertiaryFillAlt,
  tertiaryHover: colorDataVizTertiaryHover,
  tertiaryLine: colorDataVizTertiaryLine,
  warningFill: colorDataVizWarningFill,
  warningHover: colorDataVizWarningHover,
  warningLine: colorDataVizWarningLine,
};
