/**
 * THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
 */

export const radius = {
  full: '999em',
  small: '0.125rem',
};

export const borderWidth = {
  large: '0.1875rem',
  medium: '0.125rem',
  small: '0.0625rem',
};

export const color = {
  background: {
    danger: '#f5e9e8',
    primary: '#ffffff',
    secondary: '#f4f4f5',
    sideNav: '#021c6b',
    success: '#ddefe6',
    surface: '#ffffff',
    tertiary: '#e4e6e7',
    topNav: '#1f3987',
    warning: '#fbede7',
  },
  border: {
    danger: '#b4362f',
    disabled: '#f4f4f5',
    primary: '#e4e6e7',
    success: '#0b6b3d',
    warning: '#f45e1e',
  },
  brand: {
    default: '#0072ec',
    active:
      'linear-gradient(0deg, rgba(9, 21, 33, 0.4), rgba(9, 21, 33, 0.4)), linear-gradient(90deg, #0072ec 0%, #4e00c6 163.65%, #8c18e2  191.59%)',
    hover:
      'linear-gradient(0deg, rgba(9, 21, 33, 0.2), rgba(9, 21, 33, 0.2)), linear-gradient(90deg, #0072ec 0%, #4e00c6 163.65%, #8c18e2  191.59%)',
    gradient: 'linear-gradient(90deg, #0072ec 0%, #4e00c6 163.65%, #8c18e2  191.59%)',
  },
  dataViz: {
    dangerFill: '#e3837d',
    dangerHover: '#b4362f',
    dangerLine: '#d44037',
    neutralFill: '#d1d3d6',
    neutralHover: '#898e94',
    primaryFill: '#7785db',
    primaryFillAlt: '#c7ccf0',
    primaryHover: '#3442bc',
    primaryLine: '#3142c8',
    secondaryFill: '#62a9f4',
    secondaryFillAlt: '#c9e1fb',
    secondaryHover: '#005cbe',
    secondaryLine: '#0072ec',
    tertiaryFill: '#b16fed',
    tertiaryFillAlt: '#ddd0f3',
    tertiaryHover: '#8110dc',
    tertiaryLine: '#8c18e2',
    warningFill: '#ff9365',
    warningHover: '#f45e1e',
    warningLine: '#ff6422',
  },
  palette: {
    black: '#091521',
    white: '#ffffff',
    blue: {
      '50': '#ecf4fe',
      '100': '#c9e1fb',
      '200': '#95c5f8',
      '300': '#62a9f4',
      '400': '#308df1',
      '500': '#0072ec',
      '600': '#005cbe',
      '700': '#00458e',
      '800': '#003772',
      '900': '#002956',
    },
    brown: {
      '50': '#faf0e7',
      '100': '#ead9ce',
      '200': '#d8c1b2',
      '300': '#c4a794',
      '400': '#b3917b',
      '500': '#a27c62',
      '600': '#95715a',
      '700': '#84634f',
      '800': '#755646',
      '900': '#64473a',
    },
    green: {
      '50': '#ddefe6',
      '100': '#c3e1d2',
      '200': '#93c9ae',
      '300': '#62b08b',
      '400': '#329867',
      '500': '#0e864c',
      '600': '#0b6b3d',
      '700': '#095731',
      '800': '#074326',
      '900': '#06361e',
    },
    grey: {
      '50': '#fafafb',
      '100': '#f4f4f5',
      '200': '#e4e6e7',
      '300': '#d1d3d6',
      '400': '#a9adb1',
      '500': '#898e94',
      '600': '#697078',
      '700': '#49515a',
      '800': '#2a343f',
      '900': '#091521',
    },
    indigo: {
      '50': '#e9eafa',
      '100': '#c7ccf0',
      '200': '#a5aee8',
      '300': '#7785db',
      '400': '#5c6cd6',
      '500': '#3142c8',
      '600': '#3442bc',
      '700': '#2e39ad',
      '800': '#232b9c',
      '900': '#16158d',
    },
    orange: {
      '50': '#fbede7',
      '100': '#ffd0bc',
      '200': '#ffb291',
      '300': '#ff9365',
      '400': '#ff7b43',
      '500': '#ff6422',
      '600': '#f45e1e',
      '700': '#e65719',
      '800': '#d85015',
      '900': '#bf420c',
    },
    pink: {
      '50': '#fbe5ee',
      '100': '#f6bed6',
      '200': '#f194ba',
      '300': '#ed6a9f',
      '400': '#ea4c89',
      '500': '#e83274',
      '600': '#d72f70',
      '700': '#c02c69',
      '800': '#aa2964',
      '900': '#852259',
    },
    purple: {
      '50': '#f2e7fc',
      '100': '#ddd0f3',
      '200': '#c79bf2',
      '300': '#b16fed',
      '400': '#9e4ae8',
      '500': '#8c18e2',
      '600': '#8110dc',
      '700': '#7300d3',
      '800': '#6500ce',
      '900': '#4e00c6',
    },
    red: {
      '50': '#f5e9e8',
      '100': '#f4cfcd',
      '200': '#eca9a5',
      '300': '#e3837d',
      '400': '#da5d55',
      '500': '#d44037',
      '600': '#b4362f',
      '700': '#942d27',
      '800': '#75231e',
      '900': '#551a16',
    },
    yellow: {
      '50': '#fefae7',
      '100': '#fbf1c4',
      '200': '#f8e99f',
      '300': '#f4e07b',
      '400': '#f0d961',
      '500': '#ecd348',
      '600': '#dcc243',
      '700': '#c8ac3d',
      '800': '#b39638',
      '900': '#90722f',
    },
  },
  primary: {
    default: '#3142c8',
    active: '#16158d',
    hover: '#2e39ad',
  },
  text: {
    contrast: '#ffffff',
    danger: '#b4362f',
    disabled: '#a9adb1',
    primary: '#091521',
    secondary: '#49515a',
    success: '#0b6b3d',
    tertiary: '#898e94',
    warning: '#f45e1e',
  },
};

export const shadow = {
  large: '0px -1px 2px rgba(61, 58, 180, 0.1), 0px 6px 14px rgba(61, 58, 180, 0.15)',
  medium: '0px -1px 2px rgba(61, 58, 180, 0.1), 0px 4px 5px rgba(61, 58, 180, 0.15)',
  small: '0px -1px 2px rgba(61, 58, 180, 0.1), 0px 1px 2px rgba(61, 58, 180, 0.4)',
};

export const zIndex = {
  dialog: 6000,
  dropdown: 7000,
  modal: 9000,
  overlay: 8000,
  popover: 5000,
  sticky: 100,
  toast: 10000,
  tooltip: 6000,
};

export const size = {
  large: '87.5rem',
  medium: '80rem',
  small: '60rem',
  'x-large': '120rem',
  'x-small': '40.625rem',
};

export const space = {
  medium: '1rem',
  small: '0.5rem',
  large: '1.5rem',
  'x-large': '2rem',
  'x-small': '0.25rem',
};

export const fontFamily = {
  mono: '"Fira Mono", Courier, monospace',
  text: '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif',
};

export const fontSize = {
  large: '1.25rem',
  medium: '1rem',
  small: '0.875rem',
  'x-large': '1.5rem',
  'x-small': '0.75rem',
  'xx-large': '2rem',
};

export const fontWeight = {
  bold: 700,
  regular: 400,
  semibold: 600,
};

export const letterSpacing = {
  large: '0em',
  medium: '-0.01em',
  small: '-0.02em',
  'x-small': '-0.03em',
};

export const lineHeight = {
  large: '1.875rem',
  medium: '1.5rem',
  small: '1.25rem',
  'x-large': '2rem',
  'x-small': '1.125rem',
  'xx-large': '2.625rem',
};
