name: Bug Report
description: 'Create a bug report'
title: '[Bug]: '
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.

        Before submitting a new report, please review the open/closed tickets just in case this issue has already been addressed or reported.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Tell us more about the issue you are seeing.
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Link to reproduction
      description: Provide us a reproduction of the issue using [codeSandbox](https://codesandbox.io/).
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How do we re-create the bug using the link above?'
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: Please confirm the following
      options:
        - label: I agree to the [Code of
            Conduct](https://github.com/project44/manifest/blob/main/.github/CODE_OF_CONDUCT.md).
          required: true
        - label: I have reviewed the [current issues](https://github.com/project44/manifest/issues)
            for duplicate tickets.
