name: Feature request
description: Request new features, enhancments or changes.
title: '[Feature Request]: '
labels: [feature request]
body:
  - type: markdown
    attributes:
      value:
        Use the template for requesting new features, enhancements or changes. If you need to report
        and issue, please use the bug report template instead.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature, enhancement or changes you wish to see.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Examples
      description: Provide any links (if available) of examples or supporting materials.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: Please confirm the following
      options:
        - label: I agree to the [Code of
            Conduct](https://github.com/project44/manifest/blob/main/.github/CODE_OF_CONDUCT.md).
          required: true
        - label: I have reviewed the [current issues](https://github.com/project44/manifest/issues)
            for duplicate tickets.
