// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from '@project44-manifest/react-icon';

export const Add = createIcon(
  <path
    clipRule="evenodd"
    d="M12.9 7a.9.9 0 1 0-1.8 0v4.604H6.5a.9.9 0 0 0 0 1.8h4.6V18a.9.9 0 0 0 1.8 0v-4.598h4.6a.9.9 0 1 0 0-1.8h-4.6v-4.6Z"
    fillRule="evenodd"
  />,
);
