// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from '@project44-manifest/react-icon';

export const ChevronLeftDouble = createIcon(
  <path
    clipRule="evenodd"
    d="M11.42 9.246a.9.9 0 1 0-1.273-1.272l-3.392 3.391a.9.9 0 0 0 0 1.273l3.392 3.392a.9.9 0 0 0 1.273-1.273l-2.756-2.755 2.756-2.756Zm5.811 5.51a.9.9 0 1 1-1.273 1.274l-3.391-3.392a.9.9 0 0 1 0-1.273l3.391-3.391a.9.9 0 1 1 1.273 1.272l-2.755 2.756 2.755 2.755Z"
    fillRule="evenodd"
  />,
);
