// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from '@project44-manifest/react-icon';

export const ClipboardWithArrow = createIcon(
  <path
    clipRule="evenodd"
    d="M7.135 4.357a.9.9 0 0 1 .9-.9h7.93a.9.9 0 0 1 .9.9v.36h1.525a.9.9 0 0 1 .9.9v15.12a.9.9 0 0 1-.9.9H5.61a.9.9 0 0 1-.9-.9V5.617a.9.9 0 0 1 .9-.9h1.525v-.36Zm9.73 2.458v-.297h.625v13.319H6.51V6.517h.625v.298a.9.9 0 0 0 .9.9h7.93a.9.9 0 0 0 .9-.9Zm-7.93-1.558v.658h6.13v-.658h-6.13Zm5.877 9.48a.9.9 0 1 0-1.275-1.27l-.637.638v-2.83a.9.9 0 1 0-1.8 0v2.83l-.636-.639a.9.9 0 0 0-1.275 1.27l2.174 2.183a.9.9 0 0 0 1.275 0l2.174-2.182Z"
    fillRule="evenodd"
  />,
);
