// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from '@project44-manifest/react-icon';

export const Clock = createIcon(
  <>
    <path
      clipRule="evenodd"
      d="M12.105 8.28a.9.9 0 0 1 .9.9v3.432l2.79 2.79a.9.9 0 0 1-1.273 1.272l-2.995-2.994a1.1 1.1 0 0 1-.322-.778V9.179a.9.9 0 0 1 .9-.9Z"
      fillRule="evenodd"
    />
    <circle cx="12.337" cy="12.609" r="9.099" stroke="#091521" strokeWidth="1.8" />
  </>,
);
