// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from '@project44-manifest/react-icon';

export const Collapsed = createIcon(
  <path
    clipRule="evenodd"
    d="M15.69 7.392a.9.9 0 1 1 1.8 0v9.236a.9.9 0 0 1-1.8 0V7.392Zm-8.881.648A.9.9 0 1 1 8.08 6.767l4.597 4.596a.9.9 0 0 1 0 1.273L8.08 17.232a.9.9 0 1 1-1.27-1.272L10.77 12 6.81 8.04Z"
    fillRule="evenodd"
  />,
);
