// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from '@project44-manifest/react-icon';

export const Expanded = createIcon(
  <path
    clipRule="evenodd"
    d="M8.345 7.392a.9.9 0 1 0-1.8 0v9.236a.9.9 0 0 0 1.8 0V7.392Zm8.88.648a.9.9 0 1 0-1.272-1.273l-4.597 4.596a.9.9 0 0 0 0 1.273l4.597 4.596a.9.9 0 1 0 1.273-1.272L13.266 12l3.96-3.96Z"
    fillRule="evenodd"
  />,
);
