// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from '@project44-manifest/react-icon';

export const EyeOpen = createIcon(
  <path
    clipRule="evenodd"
    d="M2.146 12.32A.897.897 0 0 1 2.1 12a.898.898 0 0 1 .046-.32C2.908 9.396 5.929 4.89 12 4.89c6.07 0 9.092 4.506 9.854 6.792.035.106.05.214.045.32a.896.896 0 0 1-.045.32c-.762 2.285-3.783 6.792-9.854 6.792s-9.092-4.507-9.854-6.793ZM16.808 12a4.808 4.808 0 1 1-9.616 0 4.808 4.808 0 0 1 9.616 0ZM12 14.918a2.918 2.918 0 1 0 0-5.836 2.918 2.918 0 0 0 0 5.836Z"
    fillRule="evenodd"
  />,
);
