// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from '@project44-manifest/react-icon';

export const Folder = createIcon(
  <path
    clipRule="evenodd"
    d="M4.818 4.736a1.9 1.9 0 0 0-1.9 1.9v10.728a1.9 1.9 0 0 0 1.9 1.9h14.364a1.9 1.9 0 0 0 1.9-1.9V6.636a1.9 1.9 0 0 0-1.9-1.9H4.818Zm-.1 1.9a.1.1 0 0 1 .1-.1H12v1.6a.5.5 0 0 0 .5.5h6.782v8.728a.1.1 0 0 1-.1.1H4.818a.1.1 0 0 1-.1-.1V6.636Z"
    fillRule="evenodd"
  />,
);
