// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from '@project44-manifest/react-icon';

export const InfoNoCircle = createIcon(
  <path
    clipRule="evenodd"
    d="M12 7.1A1.05 1.05 0 1 0 12 5a1.05 1.05 0 0 0 0 2.1Zm-3.353 3.023a.9.9 0 0 1 .9-.9H12a.9.9 0 0 1 .896.991.91.91 0 0 1 .004.091v6.893h1.553a.9.9 0 0 1 0 1.8H9.547a.9.9 0 1 1 0-1.8H11.1v-6.175H9.547a.9.9 0 0 1-.9-.9Z"
    fillRule="evenodd"
  />,
);
