// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from '@project44-manifest/react-icon';

export const List = createIcon(
  <path
    clipRule="evenodd"
    d="M6.699 8.911a1.199 1.199 0 1 0 0-2.397 1.199 1.199 0 0 0 0 2.397Zm0 4.296a1.199 1.199 0 1 0 0-2.397 1.199 1.199 0 0 0 0 2.397Zm1.199 3.095a1.199 1.199 0 1 1-2.398 0 1.199 1.199 0 0 1 2.398 0Zm1.935-5.195a.9.9 0 0 0 0 1.8h7.728a.9.9 0 0 0 0-1.8H9.833Zm-.9-3.403a.9.9 0 0 1 .9-.9h7.728a.9.9 0 0 1 0 1.8H9.833a.9.9 0 0 1-.9-.9Zm.9 7.69a.9.9 0 0 0 0 1.8h7.728a.9.9 0 0 0 0-1.8H9.833Z"
    fillRule="evenodd"
  />,
);
