// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from '@project44-manifest/react-icon';

export const ListWithArrow = createIcon(
  <>
    <rect height="14" rx="1" stroke="#091521" strokeWidth="1.8" width="18" x="3" y="5.5" />
    <path d="M15.018 14.204 13.314 12.5m0 0 1.704-1.704M13.314 12.5h4.91" />
    <path
      clipRule="evenodd"
      d="M5.5 10.066a.9.9 0 0 1 .9-.9h4.379a.9.9 0 0 1 0 1.8H6.4a.9.9 0 0 1-.9-.9Zm0 2.438a.9.9 0 0 1 .9-.9h4.379a.9.9 0 0 1 0 1.8H6.4a.9.9 0 0 1-.9-.9Zm.9 1.53a.9.9 0 1 0 0 1.8h4.379a.9.9 0 0 0 0-1.8H6.4Z"
      fillRule="evenodd"
    />
  </>,
);
