// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from '@project44-manifest/react-icon';

export const Parcel = createIcon(
  <>
    <path d="M9.753 11.121a.9.9 0 1 0 0 1.8h4.494a.9.9 0 0 0 0-1.8H9.753Z" />
    <path
      clipRule="evenodd"
      d="M6.723 3.91c-.4 0-.77.217-.963.568L4.046 7.585a1.1 1.1 0 0 0-.137.531v10.875a1.1 1.1 0 0 0 1.1 1.1h13.982a1.1 1.1 0 0 0 1.1-1.1V8.116a1.1 1.1 0 0 0-.137-.531L18.24 4.478a1.1 1.1 0 0 0-.963-.569H6.723Zm.414 1.8H11.1v1.823H6.13l1.007-1.824ZM5.709 9.332v8.958h12.582V9.333H5.71Zm12.16-1.8-1.005-1.824H12.9v1.824h4.97Z"
      fillRule="evenodd"
    />
  </>,
);
