// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from '@project44-manifest/react-icon';

export const TrashCan = createIcon(
  <path
    clipRule="evenodd"
    d="M8.4 3a.9.9 0 0 0 0 1.8h7.201a.9.9 0 1 0 0-1.8h-7.2ZM4.8 7.05a.9.9 0 0 1 .9-.9h12.6a.9.9 0 1 1 0 1.8h-.45V19.9a1.1 1.1 0 0 1-1.1 1.1h-9.5a1.1 1.1 0 0 1-1.1-1.1V7.95H5.7a.9.9 0 0 1-.9-.9Zm3.15.9h8.1V19.2h-8.1V7.95Z"
    fillRule="evenodd"
  />,
);
