// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from '@project44-manifest/react-icon';

export const TrendingUp = createIcon(
  <>
    <rect height="18" rx="2" width="18" x="3" y="3" />
    <path
      clipRule="evenodd"
      d="M9.435 7.734a.9.9 0 0 1 .9-.9h5.898a.9.9 0 0 1 .9.9v5.898a.9.9 0 1 1-1.8 0V9.907L8.37 16.869a.9.9 0 1 1-1.273-1.273l6.962-6.962h-3.725a.9.9 0 0 1-.9-.9Z"
      fillRule="evenodd"
    />
  </>,
);
