// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from '@project44-manifest/react-icon';

export const TrendingDown = createIcon(
  <>
    <path d="M3 5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5Z" />
    <path
      clipRule="evenodd"
      d="M16.233 9.435a.9.9 0 0 1 .9.9v5.898a.9.9 0 0 1-.9.9h-5.898a.9.9 0 0 1 0-1.8h3.725L7.098 8.37a.9.9 0 0 1 1.273-1.273l6.962 6.962v-3.725a.9.9 0 0 1 .9-.9Z"
      fillRule="evenodd"
    />
  </>,
);
