// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from '@project44-manifest/react-icon';

export const TriangleLeft = createIcon(
  <path d="M13.715 7.423a.5.5 0 0 1 .854.354v8.448a.5.5 0 0 1-.854.353l-4.224-4.224a.5.5 0 0 1 0-.707l4.224-4.224Z" />,
);
