// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from '@project44-manifest/react-icon';

export const VerticalBars = createIcon(
  <path d="M12.875 6.234a.9.9 0 1 0-1.8 0h1.8Zm-1.8 0v12.531h1.8V6.235h-1.8ZM8.4 8.192a.9.9 0 0 0-1.8 0h1.8Zm-1.8 0v10.573h1.8V8.192H6.6ZM17.4 12.5a.9.9 0 1 0-1.8 0h1.8Zm-1.8 0v6.265h1.8V12.5h-1.8Z" />,
);
