// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from '@project44-manifest/react-icon';

export const WifiEmpty = createIcon(
  <path d="M12.034 17.994a.15.15 0 0 1-.21 0L3.94 10.112l-.636.636.636-.636a.13.13 0 0 1-.041-.092c0-.013.003-.022.005-.027a.047.047 0 0 1 .014-.016c4.633-3.971 11.476-4.019 16.162-.143a.044.044 0 0 1 .014.016.065.065 0 0 1 .005.027.13.13 0 0 1-.04.093l-8.026 8.024Z" />,
);
