module.exports = {
	rules: {
		'class-methods-use-this': 'off',
		complexity: ['error', 20],
		indent: ['error', 'tab'],
		'logical-assignment-operators': 'error',
		'multiline-comment-style': 'off',
		'no-constant-binary-expression': 'error',
		'no-constant-condition': 'error',
		'no-constructor-return': 'error',
		'no-div-regex': 'error',
		'no-dupe-else-if': 'error',
		'no-implicit-coercion': 'error',
		'no-import-assign': 'error',
		'no-magic-numbers': 'off',
		'no-native-reassign': 'error',
		'no-promise-executor-return': 'error',
		'no-restricted-syntax': 'off',
		'no-setter-return': 'error',
		'no-tabs': 'off',
		'no-unreachable-loop': 'error',
		'no-unsafe-optional-chaining': ['error', { disallowArithmeticOperators: true }],
		'no-unused-private-class-members': 'error',
		'no-useless-call': 'error',
		'no-invalid-this': 'off',
		'prefer-destructuring': [
			'error',
			{
				object: true,
				array: false,
			},
		],
		'prefer-exponentiation-operator': 'error',
		'prefer-object-has-own': 'error',
		'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
		'require-atomic-updates': 'error',
		'require-unicode-regexp': 'off',
		'sort-keys': ['off', 'asc', { caseSensitive: false, natural: true }],
	},
};
