// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const ArrowRight = createIcon(
  <path
    fillRule="evenodd"
    d="M13.51 7.336a.9.9 0 0 1 1.272 0l4.867 4.866a.9.9 0 0 1 0 1.273l-4.867 4.867a.9.9 0 0 1-1.272-1.273l3.33-3.33H4.987a.9.9 0 1 1 0-1.8H16.84l-3.33-3.33a.9.9 0 0 1 0-1.273Z"
    clipRule="evenodd"
  />,
);
