// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const BackslashCircleFilled = createIcon(
  <path
    fillRule="evenodd"
    d="M12 24c6.627 0 12-5.373 12-12S18.627 0 12 0 0 5.373 0 12s5.373 12 12 12ZM9.238 7.965a.9.9 0 0 0-1.273 1.273l6.797 6.797a.9.9 0 1 0 1.273-1.273L9.238 7.965Z"
    clipRule="evenodd"
  />,
);
