// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const CheckDouble = createIcon(
  <path
    clipRule="evenodd"
    d="m16.436 8.405-4.52 4.52-1.273-1.274 4.52-4.52a.9.9 0 1 1 1.273 1.274Zm-8.48 5.934L9.23 15.61l-1.256 1.257a.9.9 0 0 1-1.273 0L2.363 12.53a.9.9 0 1 1 1.273-1.273l3.7 3.7.62-.62Zm13.68-5.934a.9.9 0 1 0-1.273-1.273l-7.827 7.827-3.7-3.7a.9.9 0 1 0-1.273 1.273l4.337 4.336a.9.9 0 0 0 1.273 0l8.463-8.463Z"
    fillRule="evenodd"
  />,
);
