// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const CheckCircleFilled = createIcon(
  <path
    clipRule="evenodd"
    d="M12 24c6.627 0 12-5.373 12-12S18.627 0 12 0 0 5.373 0 12s5.373 12 12 12Zm6.274-15.17A.9.9 0 1 0 17 7.557l-6.838 6.838L7 11.231a.9.9 0 0 0-1.273 1.272l3.8 3.801a.9.9 0 0 0 1.274 0l7.474-7.474Z"
    fillRule="evenodd"
  />,
);
