// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const ChevronUp = createIcon(
  <path
    clipRule="evenodd"
    d="M17.233 14.04a.9.9 0 0 1-1.273 0L12 10.08l-3.96 3.96a.9.9 0 1 1-1.273-1.273l4.596-4.597a.9.9 0 0 1 1.273 0l4.597 4.597a.9.9 0 0 1 0 1.273Z"
    fillRule="evenodd"
  />,
);
