// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const ChevronRightDouble = createIcon(
  <path
    fillRule="evenodd"
    d="M12.567 9.246a.9.9 0 0 1 1.272-1.272l3.392 3.391a.9.9 0 0 1 0 1.273L13.84 16.03a.9.9 0 0 1-1.272-1.273l2.755-2.755-2.755-2.756Zm-5.812 5.51a.9.9 0 0 0 1.273 1.274l3.392-3.392a.9.9 0 0 0 0-1.273L8.028 7.974a.9.9 0 1 0-1.273 1.272l2.756 2.756-2.756 2.755Z"
    clipRule="evenodd"
  />,
);
