// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const ChevronRight = createIcon(
  <path
    fillRule="evenodd"
    d="M10.46 17.233a.9.9 0 0 1 0-1.273L14.42 12l-3.96-3.96a.9.9 0 1 1 1.273-1.273l4.596 4.596a.9.9 0 0 1 0 1.273l-4.596 4.597a.9.9 0 0 1-1.273 0Z"
    clipRule="evenodd"
  />,
);
