// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const Close = createIcon(
  <path
    fillRule="evenodd"
    d="M8.394 7.621A.9.9 0 1 0 7.12 8.894l3.606 3.606-3.606 3.606a.9.9 0 1 0 1.273 1.273L12 13.773l3.606 3.606a.9.9 0 1 0 1.273-1.273L13.273 12.5l3.606-3.606a.9.9 0 0 0-1.273-1.273L12 11.227 8.394 7.621Z"
    clipRule="evenodd"
  />,
);
