// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const Columns = createIcon(
  <path
    clipRule="evenodd"
    d="M7 5.933C7 5.018 7.669 4 8.8 4h6.4C16.331 4 17 5.018 17 5.933v12.134c0 .915-.669 1.933-1.8 1.933H8.8C7.669 20 7 18.982 7 18.067V5.933ZM9 6v12h6V6H9ZM3 17.5h2c.55 0 1-.45 1-1v-9c0-.55-.45-1-1-1H3c-.55 0-1 .45-1 1v9c0 .55.45 1 1 1Zm15-1v-9c0-.55.45-1 1-1h2c.55 0 1 .45 1 1v9c0 .55-.45 1-1 1h-2c-.55 0-1-.45-1-1Z"
    fillRule="evenodd"
  />,
);
