// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const Deactivate = createIcon(
  <path
    clipRule="evenodd"
    d="M3.9 12a8.1 8.1 0 0 1 13.156-6.329L5.67 17.056A8.066 8.066 0 0 1 3.9 12Zm3.044 6.329A8.1 8.1 0 0 0 18.33 6.944L6.944 18.33ZM12 2.1c-5.468 0-9.9 4.432-9.9 9.9s4.432 9.9 9.9 9.9 9.9-4.432 9.9-9.9-4.432-9.9-9.9-9.9Z"
    fillRule="evenodd"
  />,
);
