// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const ExclamationPoint = createIcon(
  <path
    fillRule="evenodd"
    d="M12.9 6.402a.9.9 0 0 0-1.8 0v8a.9.9 0 0 0 1.8 0v-8ZM12 19.936a1.25 1.25 0 1 0 0-2.5 1.25 1.25 0 0 0 0 2.5Z"
    clipRule="evenodd"
  />,
);
