// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const Flatbed = createIcon(
  <path
    fillRule="evenodd"
    d="M15.083 6.725a.9.9 0 0 0-.9.9v5.498H8.692a2.888 2.888 0 0 0-1.828-.648c-.692 0-1.328.243-1.827.648H2.9a.9.9 0 0 0 0 1.8H4a2.9 2.9 0 1 0 5.73 0h5.504a2.9 2.9 0 1 0 5.73 0h.135a.9.9 0 0 0 .9-.9v-2.568a.9.9 0 0 0-.266-.64l-3.867-3.83a.9.9 0 0 0-.633-.26h-2.149Zm4.843 6.398h.272V11.83l-3.337-3.305h-.878v4.598h.288a2.888 2.888 0 0 1 1.827-.648c.693 0 1.329.243 1.828.648ZM6.864 14.275a1.1 1.1 0 1 0 0 2.2 1.1 1.1 0 0 0 0-2.2Zm11.234 0a1.1 1.1 0 1 0 0 2.2 1.1 1.1 0 0 0 0-2.2Z"
    clipRule="evenodd"
  />,
);
