// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const InfoCircleFilled = createIcon(
  <path
    clipRule="evenodd"
    d="M24 12c0 6.627-5.373 12-12 12S0 18.627 0 12 5.373 0 12 0s12 5.373 12 12Zm-12.9-.38h-.954a.9.9 0 0 1 0-1.8H12a.9.9 0 0 1 .897.97.936.936 0 0 1 .003.07v4.99h.954a.9.9 0 0 1 0 1.8h-3.708a.9.9 0 0 1 0-1.8h.954v-4.23Zm1.813-3.958a1.112 1.112 0 1 1-2.224 0 1.112 1.112 0 0 1 2.224 0Z"
    fillRule="evenodd"
  />,
);
