// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const JumpToEntity = createIcon(
  <path
    fillRule="evenodd"
    d="M6.496 4.384a.9.9 0 0 0-1.8 0v16.2a.9.9 0 0 0 1.8 0v-16.2Zm11.904-.9a.9.9 0 0 1 .9.9v16.2a.9.9 0 0 1-1.8 0v-16.2a.9.9 0 0 1 .9-.9ZM10.3 5.3v14.4h3.4V5.3h-3.4ZM8.7 3.5a.2.2 0 0 0-.2.2v17.6c0 .11.09.2.2.2h6.6a.2.2 0 0 0 .2-.2V3.7a.2.2 0 0 0-.2-.2H8.7Z"
    clipRule="evenodd"
  />,
);
