// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const Key = createIcon(
  <path
    fillRule="evenodd"
    d="M18.636 5.364a.9.9 0 0 0-1.272 0l-2.5 2.5-3.594 3.593a4.9 4.9 0 1 0 1.273 1.273L15.5 9.773l.864.863a.9.9 0 0 0 1.272-1.272l-.863-.864L18 7.273l.864.863a.9.9 0 0 0 1.272-1.272l-1.5-1.5ZM5.4 15.5a3.1 3.1 0 1 1 6.2 0 3.1 3.1 0 0 1-6.2 0Z"
    clipRule="evenodd"
  />,
);
