// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const ListWithArrow = createIcon(
  <path
    fillRule="evenodd"
    d="M2 5.5a1 1 0 0 1 1-1h18a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1v-14Zm1.892.893h16.216v12.214H3.892V6.393Zm1.34 3.664a.9.9 0 0 1 .9-.9h4.386a.9.9 0 1 1 0 1.8H6.131a.9.9 0 0 1-.9-.9Zm0 2.443a.9.9 0 0 1 .9-.9h4.386a.9.9 0 1 1 0 1.8H6.131a.9.9 0 0 1-.9-.9Zm0 2.443a.9.9 0 0 1 .9-.9h4.386a.9.9 0 1 1 0 1.8H6.131a.9.9 0 0 1-.9-.9Zm10.137-4.765a.9.9 0 0 1 0 1.272l-.152.152h2.652a.9.9 0 0 1 0 1.8H15.22l.149.148a.9.9 0 0 1-1.273 1.273l-1.665-1.666a.897.897 0 0 1 0-1.314l1.665-1.665a.9.9 0 0 1 1.273 0Z"
    clipRule="evenodd"
  />,
);
