// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const Login = createIcon(
  <path
    fillRule="evenodd"
    d="M10.574 8.664a.9.9 0 1 0-1.27 1.275l1.665 1.66H3.9a.9.9 0 0 0 0 1.8h7.068l-1.666 1.66a.9.9 0 1 0 1.27 1.275l3.209-3.197a.9.9 0 0 0 0-1.275l-3.208-3.198Zm.876-3.266a.9.9 0 0 0 .9.9h5.796V18.7H12.35a.9.9 0 1 0 0 1.8h6.496a1.1 1.1 0 0 0 1.1-1.1V5.598a1.1 1.1 0 0 0-1.1-1.1H12.35a.9.9 0 0 0-.9.9Z"
    clipRule="evenodd"
  />,
);
