// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const MailOpened = createIcon(
  <path
    clipRule="evenodd"
    d="M21.05 7.644c.57.35.94.98.94 1.7l.01 10c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2v-10c0-.72.38-1.35.95-1.7l8.04-4.71c.62-.37 1.4-.37 2.02 0l8.04 4.71ZM3.74 9.184l7.2 4.5c.65.4 1.47.4 2.12 0l7.2-4.5-7.25-4.25c-.62-.37-1.4-.37-2.02 0l-7.25 4.25Z"
    fillRule="evenodd"
  />,
);
