// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const Minus = createIcon(
  <path
    fillRule="evenodd"
    d="M6.599 12a.9.9 0 0 1 .9-.9h9.003a.9.9 0 1 1 0 1.8H7.499a.9.9 0 0 1-.9-.9Z"
    clipRule="evenodd"
  />,
);
