// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const More = createIcon(
  <path
    fillRule="evenodd"
    d="M13.8 5.8a1.8 1.8 0 1 1-3.6 0 1.8 1.8 0 0 1 3.6 0Zm0 6.2a1.8 1.8 0 1 1-3.6 0 1.8 1.8 0 0 1 3.6 0ZM12 20a1.8 1.8 0 1 0 0-3.6 1.8 1.8 0 0 0 0 3.6Z"
    clipRule="evenodd"
  />,
);
