// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const Notification = createIcon(
  <path
    fillRule="evenodd"
    d="M19.29 17.04 18 15.75v-5c0-3.07-1.64-5.64-4.5-6.32v-.68c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.11 6 7.67 6 10.75v5l-1.29 1.29c-.63.63-.19 1.71.7 1.71h13.17c.9 0 1.34-1.08.71-1.71ZM8 16.75v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6H8Zm6 3a2 2 0 1 1-4 0h4Z"
    clipRule="evenodd"
  />,
);
