// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const NotificationPaused = createIcon(
  <path
    fillRule="evenodd"
    d="M19.29 17.04 18 15.75v-5c0-3.07-1.64-5.64-4.5-6.32v-.68c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.11 6 7.67 6 10.75v5l-1.29 1.29c-.63.63-.19 1.71.7 1.71h13.17c.9 0 1.34-1.08.71-1.71ZM12 21.75c1.1 0 2-.9 2-2h-4a2 2 0 0 0 2 2Zm2.2-11.83c.19-.24.3-.53.3-.84 0-.74-.59-1.33-1.32-1.33H10.4c-.5 0-.9.4-.9.9s.4.9.9.9h1.9l-2.5 3.03c-.19.24-.3.53-.3.84v.01c0 .73.59 1.32 1.32 1.32h2.78c.5 0 .9-.4.9-.9s-.4-.9-.9-.9h-1.9l2.5-3.03Z"
    clipRule="evenodd"
  />,
);
