// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const NotificationOff = createIcon(
  <path
    fillRule="evenodd"
    d="M17.305 10.75c0-3.07-1.64-5.64-4.5-6.32v-.68c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68c-.202.05-.397.122-.585.191l-.105.039 8.19 8.19v-2.1Zm-6 11c1.1 0 2-.9 2-2h-4a2 2 0 0 0 2 2Zm-8-17.24 1.41-1.41 15.98 15.98-1.41 1.41-1.74-1.74H4.715c-.89 0-1.33-1.08-.7-1.71l1.29-1.29v-5c0-1.27.29-2.43.81-3.43l-2.81-2.81Z"
    clipRule="evenodd"
  />,
);
