// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const OpenInNewTab = createIcon(
  <path
    fillRule="evenodd"
    d="M15.028 3.5a.9.9 0 1 0 0 1.8h2.9l-5.774 5.773a.9.9 0 0 0 1.273 1.273L19.2 6.573v2.9a.9.9 0 1 0 1.8 0V4.4a.9.9 0 0 0-.9-.9h-5.072Zm-3.938 0a.91.91 0 0 1 0 1.82H5.933c-.615 0-1.113.498-1.113 1.113v12.134c0 .615.498 1.113 1.113 1.113h12.134c.615 0 1.113-.498 1.113-1.113V13.38a.91.91 0 1 1 1.82 0v5.188a2.933 2.933 0 0 1-2.933 2.933H5.933A2.933 2.933 0 0 1 3 18.567V6.433A2.933 2.933 0 0 1 5.933 3.5h5.157Z"
    clipRule="evenodd"
  />,
);
