// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const Pause = createIcon(
  <path
    fillRule="evenodd"
    d="M12 3.9a8.1 8.1 0 1 0 0 16.2 8.1 8.1 0 0 0 0-16.2ZM2.1 12c0-5.468 4.432-9.9 9.9-9.9s9.9 4.432 9.9 9.9-4.432 9.9-9.9 9.9-9.9-4.432-9.9-9.9ZM10 6.6a.9.9 0 0 1 .9.9v9a.9.9 0 0 1-1.8 0v-9a.9.9 0 0 1 .9-.9Zm4.9.9a.9.9 0 0 0-1.8 0v9a.9.9 0 0 0 1.8 0v-9Z"
    clipRule="evenodd"
  />,
);
