// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const Pulse = createIcon(
  <path
    fillRule="evenodd"
    d="M14.865 7.942 10.895 18.7c-.344.932-1.648.967-2.042.056l-2.424-5.61H4a.9.9 0 1 1 0-1.8H6.89a1.1 1.1 0 0 1 1.01.663l1.913 4.427L13.89 5.384c.363-.986 1.77-.949 2.082.055l1.833 5.906H20a.9.9 0 0 1 0 1.8h-2.71a1.1 1.1 0 0 1-1.05-.774l-1.375-4.429Z"
    clipRule="evenodd"
  />,
);
