// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const Reinstate = createIcon(
  <path
    clipRule="evenodd"
    d="M3.9 12a8.1 8.1 0 1 1 16.2 0 8.1 8.1 0 0 1-16.2 0ZM12 2.1c-5.468 0-9.9 4.432-9.9 9.9s4.432 9.9 9.9 9.9 9.9-4.432 9.9-9.9-4.432-9.9-9.9-9.9ZM9.424 7.206A.9.9 0 0 0 8.1 8v8a.9.9 0 0 0 1.324.794l7.5-4a.9.9 0 0 0 0-1.588l-7.5-4ZM14.588 12 9.9 14.5v-5l4.688 2.5Z"
    fillRule="evenodd"
  />,
);
