// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const RelatedEntity = createIcon(
  <path d="m14.55 7.226-2.549 2.549h-3.18c-.49-1.35-1.89-2.26-3.46-1.93a3.013 3.013 0 0 0-2.32 2.42 3.001 3.001 0 0 0 2.96 3.51c1.3 0 2.4-.84 2.82-2h3.18L17 16.774v3c0 .55.45 1 1 1h3c.55 0 1-.45 1-1v-3c0-.55-.45-1-1-1h-2.05l-5.199-4.999L16.5 8.226h2.05c.55 0 1-.45 1-1v-3c0-.55-.45-1-1-1h-3c-.55 0-1 .45-1 1v3Z" />,
);
