// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const Reset = createIcon(
  <path
    clipRule="evenodd"
    d="M5.779 10.442A.9.9 0 1 0 7.05 9.169l-.914-.915h8.028a4.935 4.935 0 1 1 0 9.87h-7.75a.9.9 0 1 0 0 1.8h7.75a6.735 6.735 0 1 0 0-13.47H6.209l.842-.842A.9.9 0 1 0 5.78 4.34L3.364 6.754a.9.9 0 0 0 0 1.273l2.415 2.415Z"
    fillRule="evenodd"
  />,
);
