// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const Route = createIcon(
  <path
    fillRule="evenodd"
    d="M5.95 5.298a1.23 1.23 0 1 0 0 2.46 1.23 1.23 0 0 0 0-2.46Zm-3.03 1.23a3.03 3.03 0 0 1 5.906-.957h4.334a3.973 3.973 0 1 1 0 7.946h-1.147v-.001h-1.092a2.173 2.173 0 1 0 0 4.346h4.34a2.951 2.951 0 1 1 .134 1.8h-4.474a3.973 3.973 0 1 1 0-7.946h2.239a2.173 2.173 0 0 0 0-4.345H8.861a3.031 3.031 0 0 1-5.94-.843Z"
    clipRule="evenodd"
  />,
);
