// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const Search = createIcon(
  <path
    fillRule="evenodd"
    d="M5.168 10.399c0-2.885 2.332-5.22 5.204-5.22s5.204 2.335 5.204 5.22A5.21 5.21 0 0 1 14.04 14.1a5.18 5.18 0 0 1-3.668 1.517c-2.872 0-5.204-2.335-5.204-5.22Zm9.516 5.532a6.963 6.963 0 0 1-4.312 1.487c-3.87 0-7.004-3.145-7.004-7.02 0-3.874 3.134-7.02 7.004-7.02 3.87 0 7.004 3.146 7.004 7.02a7 7 0 0 1-1.429 4.25l4.422 4.434a.903.903 0 0 1 0 1.274.897.897 0 0 1-1.271 0l-4.414-4.425Z"
    clipRule="evenodd"
  />,
);
