// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const Sort = createIcon(
  <path
    fillRule="evenodd"
    d="M9.245 9.849a.9.9 0 1 1-1.273-1.273l3.392-3.392a.9.9 0 0 1 1.273 0l3.391 3.392a.9.9 0 1 1-1.272 1.273L12 7.094 9.245 9.849Zm0 5.977a.9.9 0 1 0-1.273 1.273l3.392 3.391a.9.9 0 0 0 1.272 0l3.392-3.391a.9.9 0 1 0-1.273-1.273L12 18.58l-2.755-2.755Z"
    clipRule="evenodd"
  />,
);
