// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const ThumbDown = createIcon(
  <path
    clipRule="evenodd"
    d="m2.916 11.917 3.26-7.609h8.982V14.3l-4.327 4.335 1.105-5.327H3.828a.996.996 0 0 1-.912-1.39Zm6.562 3.391-.95 4.58c-.1.5.05 1.01.41 1.37.59.58 1.53.58 2.11-.01l5.53-5.54c.37-.37.58-.88.58-1.41v-9.99c0-1.1-.9-2-2-2h-8.99c-.8 0-1.52.48-1.83 1.21l-3.26 7.61c-.85 1.98.6 4.18 2.75 4.18h5.65Zm9.69-11c0-1.1.9-2 2-2s2 .9 2 2v8c0 1.1-.9 2-2 2s-2-.9-2-2v-8Z"
    fillRule="evenodd"
  />,
);
