// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const ThumbUpFilled = createIcon(
  <path
    fillRule="evenodd"
    d="m7.409 8.292 5.54-5.54c.58-.59 1.52-.59 2.11-.01.36.36.51.87.41 1.37l-.95 4.58h5.65c2.15 0 3.6 2.2 2.76 4.18l-3.26 7.61c-.32.73-1.04 1.21-1.84 1.21h-9c-1.1 0-2-.9-2-2v-9.99c0-.53.21-1.04.58-1.41Zm-2.58 11.4c0 1.1-.9 2-2 2s-2-.9-2-2v-8c0-1.1.9-2 2-2s2 .9 2 2v8Z"
    clipRule="evenodd"
  />,
);
