// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const TrendingUp = createIcon(
  <path
    fillRule="evenodd"
    d="M5 3a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2H5Zm5.335 3.834a.9.9 0 1 0 0 1.8h3.725l-6.962 6.962a.9.9 0 1 0 1.273 1.273l6.962-6.962v3.725a.9.9 0 0 0 1.8 0V7.734a.9.9 0 0 0-.9-.9h-5.898Z"
    clipRule="evenodd"
  />,
);
