// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const TriangleRight = createIcon(
  <path d="M10.285 7.423a.5.5 0 0 0-.854.354v8.448a.5.5 0 0 0 .854.353l4.224-4.224a.5.5 0 0 0 0-.707l-4.224-4.224Z" />,
);
