// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const Warning = createIcon(
  <path
    fillRule="evenodd"
    d="M12 3.063a.9.9 0 0 1 .771.436l9.026 15.018a.9.9 0 0 1-.771 1.364H2.973a.9.9 0 0 1-.771-1.364L11.228 3.5A.9.9 0 0 1 12 3.062Zm0 2.647L4.564 18.08h14.87L12 5.71Zm0 3.023a.9.9 0 0 1 .9.9v4.174a.9.9 0 0 1-1.8 0V9.633a.9.9 0 0 1 .9-.9Zm0 8.204a.894.894 0 1 0 0-1.787.894.894 0 0 0 0 1.787Z"
    clipRule="evenodd"
  />,
);
