// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const WifiError = createIcon(
  <path
    fillRule="evenodd"
    d="M6.973 4.866A.9.9 0 1 0 5.701 6.14l1.03 1.03a13.392 13.392 0 0 0-3.398 2.124c-.44.377-.438 1.046-.028 1.456l7.882 7.882c.41.41 1.074.41 1.484 0l2.76-2.76 1.374 1.373a.9.9 0 1 0 1.273-1.273L6.973 4.866Zm13.722 5.74-2.859 2.86-7.312-7.313a13.447 13.447 0 0 1 10.13 2.988c.452.373.456 1.05.041 1.465Z"
    clipRule="evenodd"
  />,
);
