// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.
import { createIcon } from './utils/createIcon';

export const WifiEmpty = createIcon(
  <path
    fillRule="evenodd"
    d="m18.782 9.627-6.853 6.853-6.723-6.723a11.677 11.677 0 0 1 13.576-.13Zm-6.111 8.657a1.05 1.05 0 0 1-1.484 0l-7.882-7.882c-.41-.41-.412-1.079.028-1.456C8.3 4.69 15.63 4.64 20.655 8.794c.451.373.455 1.051.04 1.465l-8.024 8.025Z"
    clipRule="evenodd"
  />,
);
