/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Manifest Design System",
  "tagline": "Manifesting experiences through design",
  "favicon": "img/favicon.ico",
  "url": "https://manifestdesignsystem.com",
  "baseUrl": "/",
  "organizationName": "project44",
  "projectName": "manifest",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "plugins": [
    "docusaurus-plugin-sass"
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "breadcrumbs": false,
          "sidebarPath": "/Users/brandonclark/Development/manifest/apps/website/sidebars.js",
          "editUrl": "https://github.com/project44/manifest/tree/main/website"
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/project44/manifest/tree/main/website"
        },
        "theme": {
          "customCss": [
            "/Users/brandonclark/Development/manifest/node_modules/normalize.css/normalize.css",
            "/Users/brandonclark/Development/manifest/packages/system/tokens/lib/tokens.css",
            "/Users/brandonclark/Development/manifest/apps/website/src/styles/custom.scss"
          ]
        }
      }
    ]
  ],
  "themes": [
    "@docusaurus/theme-live-codeblock"
  ],
  "themeConfig": {
    "navbar": {
      "title": "Manifest Design System",
      "logo": {
        "alt": "Manifest Design System",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "doc",
          "docId": "index",
          "label": "Guide",
          "position": "left"
        },
        {
          "type": "doc",
          "docId": "components",
          "label": "Components",
          "position": "left"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "href": "https://github.com/project44/manifest",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Installation",
              "to": "docs/getting-started"
            },
            {
              "label": "Foundations",
              "to": "docs/foundations"
            },
            {
              "label": "Components",
              "to": "docs/components"
            },
            {
              "label": "Patterns",
              "to": "docs/patterns"
            }
          ]
        },
        {
          "title": "Resources",
          "items": [
            {
              "label": "Blog",
              "to": "/blog"
            },
            {
              "label": "Figma",
              "href": "https://www.figma.com/file/2vyIjgJEhVc1spMWwkgzQ5/Manifest-Design-System"
            }
          ]
        },
        {
          "title": "Development",
          "items": [
            {
              "label": "Contributing",
              "to": "docs/contributing"
            },
            {
              "label": "Report a bug",
              "href": "https://github.com/project44/manifest/issues/"
            },
            {
              "label": "Discussions",
              "href": "https://github.com/project44/manifest/discussions"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "project44",
              "href": "https://www.project44.com"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/project44/manifest"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2023 project44"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "liveCodeBlock": {
      "playgroundPosition": "bottom"
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
