$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  buildPackage:
    command: 'packemon'
    args:
      - 'build'
      - '--addEngines'
      - '--addExports'
      - '--declaration'
      - '--declarationConfig'
      - 'tsconfig.build.json'
    inputs:
      - '@globs(sources)'
      - '@globs(typescript)'
      - 'package.json'
    outputs:
      - 'dts'
    env:
      NODE_ENV: 'production'

  props-doc:
    command: 'node'
    args:
      - './scripts/propsDoc.mjs'
    inputs:
      - '@globs(sources)'
      - '@globs(typescript)'
      - 'package.json'
    outputs:
      - 'docs.json'
    options:
      runInCI: false
