name: Changelog

on:
  pull_request:
    paths:
      - 'packages/**'
    types:
      - opened
      - edited
      - synchronize

jobs:
  changeset:
    if: github.head_ref != 'changeset-release/main'

    name: Changeset
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Check for changeset
        run: yarn changeset status --since="origin/main"
