name: Size limit

on:
  pull_request:
    paths:
      - 'packages/**'
    types:
      - opened
      - edited
      - synchronize

jobs:
  size:
    name: Size limit
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: andresz1/size-limit-action@v1.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
