name: Size limit

on:
  pull_request:
    paths:
      - 'packages/**'
    types:
      - opened
      - edited
      - synchronize

jobs:
  size:
    name: Compressed Size
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Generate compressed bundle sizes
        uses: zahnster/compressed-size-action@2.4.2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          pattern: '**/dist/**/*.js'
          exclude: '{**/*.map,**/node_modules/**}'
